### ISSUE TITLE
Font changed after installing

### ISSUE THREAD

**Issue by celpyy** [ItzzParsher05/Super-Optimized#1]
so i installed the modpack, it helped me with my fps by ALOT (W) but the font is changed, and i cant seem to get it back to normal
![image](https://user-images.githubusercontent.com/126123508/220789889-8571b1b0-6636-41e9-83ea-a38162ffe9c5.png)

how do i fix this??

**Comment by EldraTheThird** [comment]
Well, first of all, thank you for creating the Issue.
Perhaps you mean you want to switch back to the game's default font?
Sorry I didn't check Github Notification earlier

**Comment by EldraTheThird** [comment]
If you want to switch back to the game's default font, delete ImmediatelyFast in the mods folder (this mod has features like Entities, Block entities, Particles, text rendering, GUI/HUD)

**Comment by celpyy** [comment]
tysm
